language: rust

matrix:
  include:
      - name:
        rust: stable
        script:
          - bash ci/script.sh

before_install: set -e

install:
  - bash ci/install.sh

after_script: set +e

cache: cargo

before_cache:
  - chmod -R a+r $HOME/.cargo

branches:
  only:
    - master
    - staging
    - trying

notifications:
  email:
    on_success: never
